const ActionFlags = {
    REPLACE_PRODUCTS: "REPLACE_PRODUCTS",
    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    TOGGLE_ALERT: "TOGGLE_ALERT"
}

export default ActionFlags;
